#!/usr/bin/env ruby

require 'pathname'
require 'fileutils'

xdg_config_home = Pathname(__dir__).join('../tmp/config').tap(&:mkpath)

env = {
  'XDG_CONFIG_HOME' => xdg_config_home.to_s,
}

port, password = ARGV
command = %W[obs --websocket_port=#{port} --websocket_password=#{password} --websocket_debug]

unless ENV.key?('DISPLAY')
  command.unshift 'xvfb-run', '-a', 'exec'
end

redirect = $stdin.tty? ? {} : {out: File::NULL, err: File::NULL}

exec(
  env,
  *command,
  **redirect,
)
